name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    steps:
    - name: Install dependencies
      run: |
        sudo apt install -y nasm
        sudo apt install -y valgrind

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      run: ./configure --enable-libxml2

    - name: Build
      run: make -j 8

    - name: Cache FATE
      uses: actions/cache@v2
      with:
        path: ./fate-suite
        key: fate

    - name: Update and run Fate
      run: |
        make fate-rsync SAMPLES=fate-suite/
        make fate-imf SAMPLES=fate-suite/
